---
- hosts: all
  roles:
  - systemd-networkd
  - docker
  # - kubernetes

- hosts: all
  roles:
  - wireguard
  
  handlers:
  - name: restart systemd-networkd
    systemd:
      name: systemd-networkd
      state: restarted

  tasks:
  - name: wireguard-server.netdev
    copy:
      src: wireguard-server.netdev
      dest: /etc/systemd/network/99-server.netdev
      owner: root
      group: root
      mode: 0644
    notify:
    - restart systemd-networkd

  - name: wireguard-server.network
    copy:
      src: wireguard-server.network
      dest: /etc/systemd/network/99-server.network
      owner: root
      group: root
      mode: 0644
    notify:
    - restart systemd-networkd
