apiVersion: v1
kind: Service
metadata:
  name: myvm
spec:
  selector:
    vm: myvm
  ports:
  - name: ssh
    port: 22
    protocol: TCP
    targetPort: 22
  type: LoadBalancer
---
apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachineInstance
metadata:
  name: myvm
  labels:
    vm: myvm
spec:
  terminationGracePeriodSeconds: 5
  domain:
    resources:
      requests:
        memory: 2G
    devices:
      disks:
      - name: containerdisk
        disk:
          bus: virtio
      - name: cloudinitdisk
        disk:
          bus: virtio
  volumes:
    - name: containerdisk
      containerDisk:
        image: harbor.home.nico-schieder.de/kubevirt/fedora:31
    - name: cloudinitdisk
      cloudInitNoCloud:
        userData: |
          #cloud-config
          password: fedora
          chpasswd: { expire: False }
          ssh_authorized_keys:
          - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIILXf3lXJioTlQu3GzMnZ8XiexTaNdCykstdF0EEAkg1 nschieder@notebook
          - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIDA0a+76zqpLChaUE/pFq5Pnol4ZusIkLGmhBh8ou7tq nschieder@bigbox.home.nico-schieder.de
