---
- name: Put SELinux in permissive mode, logging actions that would be blocked.
  selinux:
    policy: targeted
    state: permissive

- name: Ensure k3s
  shell: curl -sfL https://get.k3s.io | sh
