apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: ci
  namespace: concourse
spec:
  secretName: ci-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  - ci.home.nico-schieder.de
