---

- name: Docker repository
  command: dnf config-manager --add-repo https://download.docker.com/linux/fedora/docker-ce.repo
  args:
    warn: no

- name: Install docker
  dnf:
    name:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - grubby
    state: latest
  notify:
  - Enforce V1 Cgroups

- name: Start docker
  systemd:
    enabled: yes
    state: started
    name: docker
